### Numpy Array Opratinons

In [1]:
import numpy as np

#### 1D Array

In [9]:
arr = np.arange(10)
print(arr)

print("Basic Slicing: ", arr[2:7])
print("With Step: ", arr[2:7:2])
print("Negative indexing: ", arr[-3])

[0 1 2 3 4 5 6 7 8 9]
Basic Slicing:  [2 3 4 5 6]
With Step:  [2 4 6]
Negative indexing:  7


#### 2D Array

In [14]:
arr_2d = np.full((4, 4), 7)

print(arr_2d)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


 #### Using arange and reshape create a custom npm array 

In [ ]:
# Creates a 3x3 array
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
arr = np.arange(100, 110).reshape(2, 5)
print(arr)

[[100 101 102 103 104]
 [105 106 107 108 109]]


#### Using linspace and reshape 

In [39]:
arr = np.linspace(100, 110, 9).reshape(3,3)
print(arr)

[[100.   101.25 102.5 ]
 [103.75 105.   106.25]
 [107.5  108.75 110.  ]]


#### Manual initialization

In [40]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])


### How we will fo slicing with matrix

In [45]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

print("Specific Element", arr[1, 2])
print("Entire row", arr[1])
print("Entire coloum", arr[:, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element 6
Entire row [4 5 6]
Entire coloum [3 6 9]


### Sorting

In [52]:
arr = np.array([1, 4, 2, 9, 3, 4, 6, 1, 3, 6, 0, 2])
print("Sorted Array", np.sort(arr))




Sorted Array [0 1 1 2 2 3 3 4 4 6 6 9]


In [60]:
arr_2d_unsorted = np.array([[3, 1], [1, 2],[ 2 , 3]])
print(arr_2d_unsorted)
print("Sorted 2D array by column: \n", np.sort(arr_2d_unsorted, axis=0))

[[3 1]
 [1 2]
 [2 3]]
Sorted 2D array by column: 
 [[1 1]
 [2 2]
 [3 3]]


### Filters

In [65]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print(even_numbers)

[ 2  4  6  8 10]


### Filter with mask

In [67]:
mask = numbers > 5
print(mask)
print("Numbers Greater then 5:", numbers[mask])

[False False False False False  True  True  True  True  True]
Numbers Greater then 5: [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [77]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("Np where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np where [ 6  7  8  9 10]


In [79]:
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing Data

In [87]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = arr1 + arr2
print(combined)

combined = np.concatenate((arr1, arr2))
print(combined)

[5 7 9]
[1 2 3 4 5 6]


### Array compatibility

In [97]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 3])
c = np.array([7, 8, 9])

print("Compatibility shapes: ", a.shape == b.shape)
print("Compatibility shapes: ", a.shape == c.shape)

Compatibility shapes:  False
Compatibility shapes:  True


In [110]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
new_row1 = np.array([[7, 8]])

with_new_row = np.vstack((original, new_row, new_row1))
print(with_new_row)


new_col = np.array([[7], [8]])

with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 7]
 [3 4 8]]


### Delete

In [113]:
arr = np.array([1, 2, 3, 4, 5, 6])
deleted = np.delete(arr, 2)
print(deleted)

[1 2 4 5 6]
