### Numpy Phase 1

In [1]:
!uv add numpy

Resolved 35 packages in 14ms
Checked 30 packages in 7ms


In [2]:
import numpy as np
print(np.__version__)

2.4.4


#### how opration work on normal list, and numpy arrays

In [ ]:
normal_list = [1, 2, 3, 4, 5]
print(normal_list * 2)   # [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

numpy_array = np.array([1, 2, 3, 4, 5])
print(numpy_array * 2)   # [2 4 6 8 10]


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


#### Time taken, how numpy array is faster then normal list in python

In [27]:
import numpy as np
import time

start = time.time()
normal_list = [i*2 for i in range(1000)]
end = time.time()
print("--- %s seconds ---" % (end - start)) 



--- 94.93391990661621 seconds ---


#### time taken, for the numpy array   

In [26]:
import numpy as np
import time

start = time.time()
np_array = np.arange(1000) * 2
print("--- %s seconds ---" % (end - start)) 


--- -154.01314091682434 seconds ---


### Creating np array from list 

In [31]:
import numpy as np

arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Creating array from scratch 

In [35]:
zeros = np.zeros((3,6))
print(zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [78]:
zeros_1d = np.zeros(3)
print(type(zeros_1d))
print(zeros_1d.ndim)

<class 'numpy.ndarray'>
1


In [37]:
ones = np.ones((3, 6))
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [38]:
full = np.full((2, 6), 3)
print(full)

[[3 3 3 3 3 3]
 [3 3 3 3 3 3]]


In [41]:
random = np.random.random((3, 4))
print(random)

[[0.74681228 0.22146843 0.73461585 0.58349328]
 [0.67504896 0.43912585 0.21987795 0.55429592]
 [0.03397821 0.71376003 0.32454828 0.48049307]]


In [43]:
sequnce = np.arange(5,30, 2)
print(sequnce)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]


## vectors, matrix and Tensor 

#### Vector

In [82]:
vector = np.array([1, 2, 3, 4, 5, 6])
print(vector)
print(vector.ndim)

[1 2 3 4 5 6]
1


#### Matrix

In [81]:

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print(matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


#### Tensor


In [80]:

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [6, 7]]])

print(tensor)
print(tensor.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]
3


### Array Prototype

In [58]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape", arr.shape)
print("Diamention", arr.ndim)
print("Size", arr.size)
print("Data Type", arr.dtype)

Shape (2, 3)
Diamention 2
Size 6
Data Type int64


### Array reshaping

In [73]:
arr = np.arange(12)
print(arr)

reshaped = arr.reshape((3, 4))
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

# revel (return view instead of copy)
raveled = reshaped.ravel()
print(raveled)


transpose =  reshaped.transpose()
print(reshaped)
print(transpose)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
